services:
  - type: web
    name: acapra-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        fromDatabase:
          name: acapra-db
          property: connectionString
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: MAX_FILE_SIZE
        value: "5242880"

  - type: web
    name: acapra-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /api/*
        destination: https://acapra-backend.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html
